# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                     # Set to true for using managed identity
    userAssignedIdentityID: "9e5ed0e9-6405-48f7-813b-5f8fed43f92e"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "paermini-kv-test"                                 # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: csi-please-open-me
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "5960337b-a76a-4e7c-9f9c-a1139655e726"                 # The tenant ID of the key vault